[package]
name = "mini-note"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
web-sys = "0.3.74"
console_log = "1.0.0"
log = { version = "0.4" }
yew_styles = "0.11.0"
tailwind-css = "0.13.0"
trunk = "0.21.4"
wasm-bindgen = "0.2.97"